# docker compose is a tool for defining and running multi-container Docker applications
# docker compose allows to treat a group of containers as single entity, i.e. "run an app" (run an orchestrated cluster of containers) instead of "run a container"
# pip install docker-compose

# to destroy the cluster and data volumes, add -v
# docker-compose down -v

version: '3.7'  # version of docker-compose, not Python
services:
  # web is a name for a service that will be run by the container
  web:
    restart: always
    build: .
    command: python /Finance_Django_Project/manage.py runserver 0.0.0.0:8000
    volumes: # volumes mount syncs the docker filesystem with the local computer's filesystem (i.e. stores data instead of dropping at restart)
      - .:/Finance_Django_Project
    ports: # specify what port to expose
      - 8000:8000
    environment: #if the key has a $, it needs to become $$ to avoid an error
      - SECRET_KEY=e7688pwkg74i88%c6i*m0ipuf)(==l07ozf^p^jc195i6-7!cp
      - DEBUG=1
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - djangonetwork

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: finance_django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" #port that is specified in Django settings
    networks:
    - djangonetwork

  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: fantas300@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"
    networks:
      - djangonetwork


networks: 
  djangonetwork:
    driver: bridge

volumes:
  finance_django_project_data:
  postgres_data:
  pgadmin_data: