# Generated by Django 3.1.4 on 2021-01-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Queued for scraping.')),
                ('date', models.DateField()),
                ('link', models.URLField()),
                ('sentiment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=55)),
                ('search_start_date', models.DateField()),
                ('periods', models.IntegerField(choices=[('1', 1), ('2', 2)])),
                ('periodicity', models.CharField(choices=[('1D', '1D'), ('2D', '2D'), ('3D', '3D'), ('5D', '5D'), ('W', 'W'), ('2W', '2W'), ('M', 'M')], max_length=55)),
                ('google_results_pages', models.IntegerField(choices=[('1', 1), ('2', 2)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='date',
        ),
        migrations.DeleteModel(
            name='Pending',
        ),
        migrations.RemoveField(
            model_name='text',
            name='link',
        ),
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='article',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.request'),
        ),
        migrations.AddField(
            model_name='text',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.article'),
        ),
    ]
