# Generated by Django 3.1.4 on 2021-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20210103_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='google_results_pages',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
        migrations.AlterField(
            model_name='request',
            name='periods',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
    ]
