# Generated by Django 3.1.4 on 2021-01-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20210103_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='periodicity',
            field=models.CharField(choices=[('Daily', '1D'), ('Bidaily', '2D'), ('3-day', '3D'), ('5-day', '5D'), ('Weekly', 'W'), ('Biweekly', '2W'), ('Monthly', 'M')], max_length=55),
        ),
    ]
