# Generated by Django 3.1.4 on 2021-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20210104_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SCRAPER', 'SCRAPER'), ('MODEL', 'MODEL')], max_length=255)),
                ('status', models.CharField(choices=[('FREE', 'FREE'), ('BUSY', 'BUSY')], default='FREE', max_length=255)),
            ],
        ),
    ]
