# Generated by Django 3.1.4 on 2020-12-29 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('fullTimeEmployees', models.IntegerField(blank=True, null=True)),
                ('longBusinessSummary', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('t_yield', models.FloatField(blank=True, null=True)),
                ('dividendRate', models.FloatField(blank=True, null=True)),
                ('exDividendDate', models.DateField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('trailingPE', models.FloatField(blank=True, null=True)),
                ('marketCap', models.FloatField(blank=True, null=True)),
                ('ytdReturn', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('fiftyTwoWeekHigh', models.FloatField(blank=True, null=True)),
                ('forwardPE', models.FloatField(blank=True, null=True)),
                ('fiveYearAvgDividendYield', models.FloatField(blank=True, null=True)),
                ('fiftyTwoWeekLow', models.FloatField(blank=True, null=True)),
                ('dividendYield', models.FloatField(blank=True, null=True)),
                ('shortName', models.CharField(blank=True, max_length=55, null=True)),
                ('longName', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(blank=True, max_length=55, null=True)),
                ('beta3Year', models.FloatField(blank=True, null=True)),
                ('profitMargins', models.FloatField(blank=True, null=True)),
                ('enterpriseToEbitda', models.FloatField(blank=True, null=True)),
                ('morningStarRiskRating', models.FloatField(blank=True, null=True)),
                ('forwardEps', models.FloatField(blank=True, null=True)),
                ('sharesOutstanding', models.BigIntegerField(blank=True, null=True)),
                ('sharesShort', models.BigIntegerField(blank=True, null=True)),
                ('heldPercentInstitutions', models.FloatField(blank=True, null=True)),
                ('trailingEps', models.FloatField(blank=True, null=True)),
                ('lastDividendValue', models.FloatField(blank=True, null=True)),
                ('heldPercentInsiders', models.FloatField(blank=True, null=True)),
                ('shortRatio', models.FloatField(blank=True, null=True)),
                ('enterpriseValue', models.FloatField(blank=True, null=True)),
                ('morningStarOverallRating', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('kind', models.CharField(choices=[('Portfolio', 'Portfolio'), ('Watchlist', 'Watchlist')], default='Watchlist', max_length=30)),
                ('ticker', models.ManyToManyField(to='portfolio.Ticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
