# Generated by Django 3.1.4 on 2021-01-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='SandP52WeekChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='annualReportExpenseRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ask',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='askSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='averageDailyVolume10Day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='averageVolume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='averageVolume10days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='bidSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='bookValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='currency',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='dateShortInterest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='dayHigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='dayLow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='earningsQuarterlyGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='enterpriseToRevenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='exchange',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='exchangeTimezoneName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='fiftyDayAverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='fiftyTwoWeekChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='fiveYearAverageReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='floatShares',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='fundFamily',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='fundInceptionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='impliedSharesOutstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='lastDividendDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='lastFiscalYearEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='lastSplitDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='lastSplitFactor',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='legalType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='mostRecentQuarter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='navPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='netIncomeToCommon',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='nextFiscalYearEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='payoutRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='pegRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='previousClose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='priceToBook',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='priceToSalesTrailing12Months',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='quoteType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='regularMarketDayHigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='regularMarketDayLow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='regularMarketOpen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='regularMarketPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='regularMarketVolume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='revenueQuarterlyGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sharesPercentSharesOut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sharesShortPreviousMonthDate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sharesShortPriorMonth',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='shortPercentOfFloat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='threeYearAverageReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='totalAssets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='trailingAnnualDividendRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='trailingAnnualDividendYield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='twoHundredDayAverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='volume24Hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
